### ISSUE TITLE
Organizations service for public tenant

### ISSUE THREAD

**Issue by kmccarp** [moderneinc/moderne-organizations#1]
As part of this, phase out the Agent configuration for the repository groups json file.

**Comment by sjungling** [comment]
@kmccarp do we want to deploy this as an additional micro-service?

**Comment by sjungling** [comment]
per standup, yes, we'll deploy as microservice to `public` tenant

**Comment by sjungling** [comment]
Will need to add as another microservice? https://github.com/moderneinc/moderne-common/blob/main/src/main/java/io/moderne/common/ModerneMicroservice.java#L22-L33

**Comment by sjungling** [comment]
deployed a separate service to public tenant only

**Comment by sjungling** [comment]
- https://github.com/moderneinc/moderne-api-gateway/pull/198
- https://github.com/moderneinc/moderne-organizations/pull/5

**Comment by sjungling** [comment]
formally deployed to https://organizations.moderne.ninja/graphiql/index.html
